### ISSUE TITLE
No content to map due to end-of-input

### ISSUE THREAD

**Issue by liuchink** [LinWanCen/show-comment#31]
Detector org.jetbrains.plugins.textmate.TextMateFileType$TextMateFileDetector@140e03fc (class org.jetbrains.plugins.textmate.TextMateFileType$TextMateFileDetector) exception occurred:

com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (BufferedInputStream); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4821)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4723)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3714)
	at org.jetbrains.plugins.textmate.bundles.VSCBundleReaderKt.readVSCBundle(VSCBundleReader.kt:27)
	at org.jetbrains.plugins.textmate.TextMateServiceImpl.readBundle(TextMateServiceImpl.java:239)
	at org.jetbrains.plugins.textmate.TextMateServiceImpl.registerBundle(TextMateServiceImpl.java:272)
	at org.jetbrains.plugins.textmate.TextMateServiceImpl.registerBundles(TextMateServiceImpl.java:94)
	at org.jetbrains.plugins.textmate.TextMateServiceImpl.ensureInitialized(TextMateServiceImpl.java:262)
	at org.jetbrains.plugins.textmate.TextMateServiceImpl.getLanguageDescriptorByFileName(TextMateServiceImpl.java:204)
	at org.jetbrains.plugins.textmate.TextMateFileType$TextMateFileDetector.detect(TextMateFileType.java:89)
	at com.intellij.openapi.fileTypes.impl.FileTypeDetectionService.lambda$detectFromContent$5(FileTypeDetectionService.java:553)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.processTextFromBinaryPresentationOrNull(LoadTextUtil.java:571)
	at com.intellij.openapi.fileTypes.impl.FileTypeDetectionService.detectFromContent(FileTypeDetectionService.java:542)
	at com.intellij.openapi.fileTypes.impl.FileTypeDetectionService.detectFromContentAndCache(FileTypeDetectionService.java:512)
	at com.intellij.openapi.fileTypes.impl.FileTypeDetectionService.getOrDetectFromContent(FileTypeDetectionService.java:246)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.internalContinueToDetectFileTypeByFile(FileTypeManagerImpl.java:766)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:757)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:692)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:356)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getFileType(VirtualFileSystemEntry.java:594)
	at org.jetbrains.kotlin.idea.base.platforms.LibraryEffectiveKindProvider$LibraryKindScanner$ScannerVisitor.visitFile(LibraryEffectiveKindProvider.kt:94)
	at org.jetbrains.kotlin.idea.base.platforms.LibraryEffectiveKindProvider$LibraryKindScanner$Companion$runScannerOutsideScanningSession$1.visitFile(LibraryEffectiveKindProvider.kt:77)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:106)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at org.jetbrains.kotlin.idea.base.platforms.LibraryEffectiveKindProvider$LibraryKindScanner$Companion.runScannerOutsideScanningSession(LibraryEffectiveKindProvider.kt:75)
	at org.jetbrains.kotlin.idea.base.platforms.LibraryEffectiveKindProvider.getEffectiveKind(LibraryEffectiveKindProvider.kt:51)
	at org.jetbrains.kotlin.idea.base.platforms.StdlibDetectorFacility.isSupported(StdlibDetectorFacility.kt:44)
	at org.jetbrains.kotlin.idea.base.platforms.StdlibDetectorFacility.getStdlibVersion(StdlibDetectorFacility.kt:36)
	at org.jetbrains.kotlin.idea.base.platforms.IdePlatformKindProjectStructure$getLibraryVersionProvider$3.invoke(IdePlatformKindProjectStructure.kt:48)
	at org.jetbrains.kotlin.idea.base.platforms.IdePlatformKindProjectStructure$getLibraryVersionProvider$3.invoke(IdePlatformKindProjectStructure.kt:47)
	at org.jetbrains.kotlin.idea.base.compilerPreferences.facet.KotlinVersionInfoProviderByModuleDependencies.getLibraryVersions(KotlinVersionInfoProviderByModuleDependencies.kt:33)
	at org.jetbrains.kotlin.idea.facet.KotlinVersionInfoProviderKt$getRuntimeLibraryVersions$1.invoke(KotlinVersionInfoProvider.kt:35)
	at org.jetbrains.kotlin.idea.facet.KotlinVersionInfoProviderKt$getRuntimeLibraryVersions$1.invoke(KotlinVersionInfoProvider.kt:35)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at org.jetbrains.kotlin.idea.facet.KotlinVersionInfoProviderKt.getRuntimeLibraryVersions(KotlinVersionInfoProvider.kt:94)
	at org.jetbrains.kotlin.idea.facet.KotlinFacetUtils.getDefaultTargetPlatform(KotlinFacetUtils.kt:91)
	at org.jetbrains.kotlin.idea.facet.KotlinFacetUtils.initializeIfNeeded(KotlinFacetUtils.kt:53)
	at org.jetbrains.kotlin.idea.facet.KotlinFacetUtils.initializeIfNeeded$default(KotlinFacetUtils.kt:35)
	at org.jetbrains.kotlin.idea.facet.KotlinFacetSettingsProviderImpl.calculate(KotlinFacetSettingsProviderImpl.kt:33)
	at org.jetbrains.kotlin.idea.facet.KotlinFacetSettingsProviderImpl.calculate(KotlinFacetSettingsProviderImpl.kt:21)
	at org.jetbrains.kotlin.idea.base.util.caching.SynchronizedFineGrainedEntityCache.get(FineGrainedEntityCache.kt:287)
	at org.jetbrains.kotlin.idea.facet.KotlinFacetSettingsProviderImpl$getInitializedSettings$1.invoke(KotlinFacetSettingsProviderImpl.kt:29)
	at org.jetbrains.kotlin.idea.facet.KotlinFacetSettingsProviderImpl$getInitializedSettings$1.invoke(KotlinFacetSettingsProviderImpl.kt:29)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:19)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:19)
	at org.jetbrains.kotlin.idea.facet.KotlinFacetSettingsProviderImpl.getInitializedSettings(KotlinFacetSettingsProviderImpl.kt:29)
	at org.jetbrains.kotlin.idea.project.ModulePlatformCache.calculate(ModulePlatformCache.kt:27)
	at org.jetbrains.kotlin.idea.project.ModulePlatformCache.calculate(ModulePlatformCache.kt:15)
	at org.jetbrains.kotlin.idea.base.util.caching.SynchronizedFineGrainedEntityCache.get(FineGrainedEntityCache.kt:287)
	at org.jetbrains.kotlin.idea.base.facet.platform.TargetPlatformDetectorUtils$platform$1.invoke(TargetPlatformDetector.kt:37)
	at org.jetbrains.kotlin.idea.base.facet.platform.TargetPlatformDetectorUtils$platform$1.invoke(TargetPlatformDetector.kt:37)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:19)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:19)
	at org.jetbrains.kotlin.idea.base.facet.platform.TargetPlatformDetectorUtils.getPlatform(TargetPlatformDetector.kt:37)
	at org.jetbrains.kotlin.idea.base.facet.JvmOnlyProjectChecker$calculate$1.invoke(JvmOnlyProjectChecker.kt:26)
	at org.jetbrains.kotlin.idea.base.facet.JvmOnlyProjectChecker$calculate$1.invoke(JvmOnlyProjectChecker.kt:23)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:19)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:19)
	at org.jetbrains.kotlin.idea.base.facet.JvmOnlyProjectChecker.calculate(JvmOnlyProjectChecker.kt:23)
	at org.jetbrains.kotlin.idea.base.facet.JvmOnlyProjectChecker.calculate(JvmOnlyProjectChecker.kt:17)
	at org.jetbrains.kotlin.idea.base.util.caching.SynchronizedFineGrainedValueCache.calculate(FineGrainedEntityCache.kt:326)
	at org.jetbrains.kotlin.idea.base.util.caching.SynchronizedFineGrainedValueCache.calculate(FineGrainedEntityCache.kt:313)
	at org.jetbrains.kotlin.idea.base.util.caching.SynchronizedFineGrainedEntityCache.get(FineGrainedEntityCache.kt:287)
	at org.jetbrains.kotlin.idea.base.util.caching.SynchronizedFineGrainedValueCache.value(FineGrainedEntityCache.kt:324)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport.platformSourcesFirst(IDEKotlinAsJavaSupport.kt:204)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport.access$platformSourcesFirst(IDEKotlinAsJavaSupport.kt:48)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport$findFilesForFacade$1.invoke(IDEKotlinAsJavaSupport.kt:183)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport$findFilesForFacade$1.invoke(IDEKotlinAsJavaSupport.kt:182)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:19)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:19)
	at org.jetbrains.kotlin.idea.caches.resolve.IDEKotlinAsJavaSupport.findFilesForFacade(IDEKotlinAsJavaSupport.kt:182)
	at org.jetbrains.kotlin.asJava.KotlinAsJavaSupportBase.getFacadeClasses(KotlinAsJavaSupportBase.kt:95)
	at org.jetbrains.kotlin.asJava.finder.JavaElementFinder.findClasses(JavaElementFinder.kt:47)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithoutJvmFacade(JavaPsiFacadeImpl.java:162)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithJvmFacade(JavaPsiFacadeImpl.java:133)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:125)
	at com.intellij.psi.impl.file.PsiPackageImpl.findAllClasses(PsiPackageImpl.java:202)
	at com.intellij.psi.impl.file.PsiPackageImpl.getCachedClassesByName(PsiPackageImpl.java:192)
	at com.intellij.psi.impl.file.PsiPackageImpl.findClassByShortName(PsiPackageImpl.java:269)
	at com.intellij.psi.impl.file.PsiPackageImpl.processDeclarations(PsiPackageImpl.java:309)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processPackageDeclarations(PsiJavaFileBaseImpl.java:447)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processCurrentPackage(PsiJavaFileBaseImpl.java:391)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processOnDemandPackages(PsiJavaFileBaseImpl.java:369)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:299)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:61)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:40)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:207)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:136)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:492)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:378)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:371)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:176)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:214)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:176)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:845)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:837)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:813)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:426)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:420)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:355)
	at io.github.linwancen.plugin.show.lang.base.BaseLangDoc.refDoc(BaseLangDoc.java:141)
	at io.github.linwancen.plugin.show.java.JavaLangDoc.refDoc(JavaLangDoc.java:67)
	at io.github.linwancen.plugin.show.lang.base.BaseLangDoc.refElementDoc(BaseLangDoc.java:121)
	at io.github.linwancen.plugin.show.lang.base.BaseLangDoc.findRefDoc(BaseLangDoc.java:75)
	at io.github.linwancen.plugin.show.lang.base.BaseLangDoc.langDoc(BaseLangDoc.java:55)
	at io.github.linwancen.plugin.show.LineEnd.lineDoc(LineEnd.java:93)
	at io.github.linwancen.plugin.show.LineEnd.lineDocSkipHave(LineEnd.java:73)
	at io.github.linwancen.plugin.show.LineEnd.getLineExtensions(LineEnd.java:38)
	at com.intellij.openapi.editor.impl.EditorImpl.processLineExtensions(EditorImpl.java:783)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.collectExtensions(EditorPainter.java:858)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session$1.paintAfterLineEnd(EditorPainter.java:445)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.paintLineFragments(EditorPainter.java:1549)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.paintBackground(EditorPainter.java:358)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.paint(EditorPainter.java:186)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:71)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:280)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1951)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:278)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:143)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:237)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at com.intellij.openapi.fileEditor.impl.EditorTabs.paintChildren(EditorTabbedContainer.kt:572)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1101)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3983)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.kt:94)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:893)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:380)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by liuchink** [comment]
2023.1版本有这个错误，2022.3.3就没有

**Comment by LinWanCen** [comment]
这个地方是有 try catch 的，IDEA 好像用了什么特殊的方式让 try 不能把异常捕捉，可以看看更新的版本是否报错，或者用旧版，如果不报错了就 Close 下 issue 哈。
https://github.com/LinWanCen/show-comment/blob/83e0a0a5eefa9a0f134af3fa90f0eeae923ac3af/src/main/java/io/github/linwancen/plugin/show/lang/base/BaseLangDoc.java#L140-L146

**Comment by liuchink** [comment]
2.08.0.2023.06.21_08.10版本，依然还是这个问题，idea也升级到2023.1.3版本

**Comment by LinWanCen** [comment]
2.09以上对所有入口都加了 try，更新下看看是否还有类似问题。
