### ISSUE TITLE
出现空指针异常，看了下你的代码，没找到CacheUpdateEditorListener文件

### ISSUE THREAD

**Issue by zhusaidong** [LinWanCen/show-comment#51]
版本：2.13.0.2024.01.02_18.27
idea版本：idea 2023.3.2（UE）

```java
java.lang.NullPointerException: Cannot invoke "java.util.Map.remove(Object)" because "fileMap" is null
	at io.github.linwancen.plugin.show.cache.CacheUpdateEditorListener.lambda$fileClosed$2(CacheUpdateEditorListener.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by LinWanCen** [comment]
哈哈哈，昨天发的版本就是修复这个的，没想到被你先发现了，在关闭项目的时候并发关闭文件会出现，之前测试时没关闭过项目没发现，缓存版目前还有很多体验问题，代码推送不及时。
https://github.com/LinWanCen/show-comment/blob/48934406bde9bf5f1d917bea1a496a9a910436be/src/main/java/io/github/linwancen/plugin/show/cache/CacheUpdateEditorListener.java#L47-L58
