### ISSUE TITLE
在idea2024.2下报错

### ISSUE THREAD

**Issue by oday-xiexin** [LinWanCen/show-comment#60]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.github.linwancen.plugin.show.LineEndCopy' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.github.linwancen.show-comment]
        at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
        at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
        at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
        at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
        at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by oday-xiexin** [comment]
![image](https://github.com/user-attachments/assets/c3ab2dd4-b9c9-46a1-835b-f2a90dd45fb2)

**Comment by LinWanCen** [comment]
#52 已经提到这个问题

这个报错不影响使用，是因为新版 IDEA 要求 update 方法必须指定是 UI 线程还是后台线程。

我的插件都有 update 方法中英文切换，这个报错可能会导致右键菜单功能为英文。

修改比较麻烦，需要在新版本 IDEA 编译一个 class，然后用类加载来兼容，一开始官方说必须得弄两个版本分别兼容。

Cool Request 作者有指导怎么修改不过他的新版代码没开源不能直接参考，
好像 apipost 作者也跟着做了，我问问他有没有代码参考。

因为不影响使用，所以一直没动力改哈哈哈，不过倒是影响了下载量。
