### ISSUE TITLE
在编辑ideavim的配置文件时 showcomment插件抛出异常

### ISSUE THREAD

**Issue by Zim-Inn** [LinWanCen/show-comment#69]
```java
JsonJumpJava.register catch Throwable but log to record.

com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.EmptyProgressIndicatorBase.checkCanceled(EmptyProgressIndicatorBase.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.checkCancelledEvenWithPCEDisabled(ProgressIndicatorUtils.java:442)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:416)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:409)
	at com.intellij.indexing.shared.platform.impl.SharedIndexChunkConfigurationImpl.processSharedIndexes(SharedIndexChunkConfigurationImpl.java:229)
	at com.intellij.indexing.shared.platform.impl.CompositeInvertedIndex.getSecondaryIndexData(CompositeInvertedIndex.java:84)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.getData(CompositeInvertedIndexBase.java:117)
	at com.intellij.psi.stubs.StubIndexEx.lambda$getContainingIds$13(StubIndexEx.java:400)
	at com.intellij.util.indexing.IndexUpToDateCheckIn.disableUpToDateCheckIn(IndexUpToDateCheckIn.kt:15)
	at com.intellij.util.indexing.FileBasedIndexEx.disableUpToDateCheckIn(FileBasedIndexEx.java:768)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:396)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:177)
	at org.jetbrains.kotlin.idea.stubindex.KotlinStringStubIndexHelper.processElements(KotlinStringStubIndexHelper.kt:62)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache.processClassesWithName(KotlinShortNamesCache.kt:120)
	at org.jetbrains.kotlin.idea.caches.KotlinShortNamesCache.getClassesByName(KotlinShortNamesCache.kt:136)
	at com.intellij.psi.impl.CompositeShortNamesCache.getClassesByName(CompositeShortNamesCache.java:94)
	at io.github.linwancen.plugin.show.java.doc.PsiClassUtils.simpleNameToClass(PsiClassUtils.java:65)
	at io.github.linwancen.plugin.show.java.doc.PsiClassUtils.nameToClass(PsiClassUtils.java:59)
	at io.github.linwancen.plugin.show.java.doc.PsiClassUtils.encClass(PsiClassUtils.java:33)
	at io.github.linwancen.plugin.show.java.JsonJumpJava$1.getReferencesByElement(JsonJumpJava.java:61)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:164)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:145)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:124)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:173)
	at com.intellij.psi.impl.AbstractPsiCachedValue.doCompute(PsiCachedValueImpl.kt:21)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:299)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:299)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:29)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:300)
	at com.intellij.psi.impl.PsiCachedValueImpl$Direct.getValue(PsiCachedValueImpl.kt:121)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:170)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:42)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:35)
	at com.intellij.json.psi.impl.JsonLiteralMixin.getReferences(JsonLiteralMixin.java:19)
	at com.intellij.json.psi.impl.JsonLiteralImpl.getReferences(JsonLiteralImpl.java:13)
	at io.github.linwancen.plugin.show.lang.JsonLangDoc.refDoc(JsonLangDoc.java:70)
	at io.github.linwancen.plugin.show.lang.base.BaseLangDoc.refElementDoc(BaseLangDoc.java:126)
	at io.github.linwancen.plugin.show.lang.JsonLangDoc.findRefDoc(JsonLangDoc.java:57)
	at io.github.linwancen.plugin.show.lang.base.BaseLangDoc.langDoc(BaseLangDoc.java:78)
	at io.github.linwancen.plugin.show.LineEnd.lineDocSkipHave(LineEnd.java:117)
	at io.github.linwancen.plugin.show.LineEnd.lineExt(LineEnd.java:70)
	at io.github.linwancen.plugin.show.cache.LineEndCacheUtils.lambda$cacheUpdate$5(LineEndCacheUtils.java:109)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:857)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:889)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:618)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:581)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:95)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:95)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:581)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:506)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:222)
	at io.github.linwancen.plugin.show.cache.LineEndCacheUtils.lambda$cacheUpdate$6(LineEndCacheUtils.java:139)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at io.github.linwancen.plugin.show.cache.LineEndCacheUtils.lambda$cacheUpdate$7(LineEndCacheUtils.java:98)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at io.github.linwancen.plugin.show.cache.LineEndCacheUtils.lambda$cacheUpdate$8(LineEndCacheUtils.java:98)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at io.github.linwancen.plugin.show.cache.LineEndCacheUtils.cacheUpdate(LineEndCacheUtils.java:92)
	at io.github.linwancen.plugin.show.cache.LineEndCacheUtils.lambda$checkScheduleAndInit$4(LineEndCacheUtils.java:81)
	at com.intellij.util.concurrency.Propagation$capturePropagationContext$$inlined$Runnable$1.run(Runnable.kt:17)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
插件版本218.0.2024.12.23.20.58

**Comment by LinWanCen** [comment]
这个异常 try 掉了不影响，ProcessCanceledException 是因为中途有变化被 IDEA 取消 Cancel 了。
